### ISSUE TITLE
ROCm 6.0?

### ISSUE THREAD

**Issue by Jipok** [rederick29/void-packages#3]
ROCm 6.0 is a major release with new performance optimizations...
https://github.com/ROCm/ROCm/releases

**Comment by rederick29** [comment]
> ROCm 6.0 is a major release with new performance optimizations... https://github.com/ROCm/ROCm/releases

A few things have changed in building ROCm in the newer versions. I have gotten started on updating the packages to 6.0 but unfortunately it has become harder for me to test them as I have a rather old GPU that is not supported by the new version. I will push updated packages soon.

**Comment by rederick29** [comment]
@Jipok I have pushed updated packages to a new branch: https://github.com/rederick29/void-packages/tree/rocm6. 

Unfortunately I couldn't test them as I get segfault after segfault on my unsupported GPU so I cannot guarantee they work. There is also a [bug](https://github.com/ROCm/ROCm/issues/2596) that on current kernels which is not yet fixed in linux 6.7. 6.1 works. 

If you're updating from an older version, I recommending uninstalling all the old packages first (and making sure nothing is left in /opt/rocm) before installing the new version.

**Comment by Jipok** [comment]
![изображение](https://github.com/rederick29/void-packages/assets/25588359/ab5f93c5-e159-4f64-b8ee-68bbad09143d)
Is it ok?

**Comment by rederick29** [comment]
Should be OK.

**Comment by Jipok** [comment]
```
=> hipFFT-6.0.2_1: running do-fetch hook: 00-distfiles ...
=> hipFFT-6.0.2_1: fetching distfile 'hipfft.tar.gz' from 'https://github.com/ROCmSoftwarePlatform/hipFFT/archive/rocm-6.0.2.tar.gz>hipfft.tar.gz'...
hipfft.tar.gz: [0B 0%] 63MB/s ETA: unknown
hipfft.tar.gz: 167KB [avg rate: 2624MB/s]
=> hipFFT-6.0.2_1: verifying checksum for distfile 'hipfft.tar.gz'...
=> ERROR: SHA256 mismatch for 'hipfft.tar.gz:'
c0a4bac5fa9a757a19a4995fa9571328b6ee0a71e93c66a880069794d65d284a
=> hipFFT-6.0.2_1: using known distfile rocm-6.0.2.tar.gz.
=> ERROR: hipFFT-6.0.2_1: couldn't verify distfiles, exiting...
```
After change checksum to
 `c0a4bac5fa9a757a19a4995fa9571328b6ee0a71e93c66a880069794d65d284a  hostdir/sources/hipFFT-6.0.2/hipfft.tar.gz`
I got:
```
=> hipFFT-6.0.2_2: running pre-configure hook: 00-gnu-configure-asneeded ...
=> hipFFT-6.0.2_2: running pre-configure hook: 01-override-config ...
=> hipFFT-6.0.2_2: running pre-configure hook: 02-script-wrapper ...
=> hipFFT-6.0.2_2: running pre_configure ...
=> ERROR: hipFFT-6.0.2_2: pre_configure: 'rm hipFFT-rocm-${_hipfft_version}/clients/rocFFT 2> /dev/null' exited with 1
=> ERROR:   in pre_configure() at srcpkgs/hipFFT/template:31
```

**UPD:** Added `|| echo A` at end of 31th line, building now

**Comment by Jipok** [comment]
Successfully built. Works. Seems to be +25% token/sec in llama.cpp. Thanks you.
Build instruction: https://github.com/void-linux/void-packages/issues/26415#issuecomment-1702991439
